INSERT INTO "region"(code, "codecheflieu", "typenomclair", libelle, "libelleenrichi") VALUES ('01','97105','3','GUADELOUPE','Guadeloupe');
INSERT INTO "region"(code, "codecheflieu", "typenomclair", libelle, "libelleenrichi") VALUES ('02','97209','3','MARTINIQUE','Martinique');
INSERT INTO "region"(code, "codecheflieu", "typenomclair", libelle, "libelleenrichi") VALUES ('03','97302','3','GUYANE','Guyane');
INSERT INTO "region"(code, "codecheflieu", "typenomclair", libelle, "libelleenrichi") VALUES ('04','97411','0','LA REUNION','La Réunion');
INSERT INTO "region"(code, "codecheflieu", "typenomclair", libelle, "libelleenrichi") VALUES ('11','75056','1','ILE-DE-FRANCE','Île-de-France');
INSERT INTO "region"(code, "codecheflieu", "typenomclair", libelle, "libelleenrichi") VALUES ('21','51108','0','CHAMPAGNE-ARDENNE','Champagne-Ardenne');
INSERT INTO "region"(code, "codecheflieu", "typenomclair", libelle, "libelleenrichi") VALUES ('22','80021','0','PICARDIE','Picardie');
INSERT INTO "region"(code, "codecheflieu", "typenomclair", libelle, "libelleenrichi") VALUES ('23','76540','0','HAUTE-NORMANDIE','Haute-Normandie');
INSERT INTO "region"(code, "codecheflieu", "typenomclair", libelle, "libelleenrichi") VALUES ('24','45234','2','CENTRE','Centre');
INSERT INTO "region"(code, "codecheflieu", "typenomclair", libelle, "libelleenrichi") VALUES ('25','14118','0','BASSE-NORMANDIE','Basse-Normandie');
INSERT INTO "region"(code, "codecheflieu", "typenomclair", libelle, "libelleenrichi") VALUES ('26','21231','0','BOURGOGNE','Bourgogne');
INSERT INTO "region"(code, "codecheflieu", "typenomclair", libelle, "libelleenrichi") VALUES ('31','59350','2','NORD-PAS-DE-CALAIS','Nord-Pas-de-Calais');
INSERT INTO "region"(code, "codecheflieu", "typenomclair", libelle, "libelleenrichi") VALUES ('41','57463','0','LORRAINE','Lorraine');
INSERT INTO "region"(code, "codecheflieu", "typenomclair", libelle, "libelleenrichi") VALUES ('42','67482','1','ALSACE','Alsace');
INSERT INTO "region"(code, "codecheflieu", "typenomclair", libelle, "libelleenrichi") VALUES ('43','25056','0','FRANCHE-COMTE','Franche-Comté');
INSERT INTO "region"(code, "codecheflieu", "typenomclair", libelle, "libelleenrichi") VALUES ('52','44109','4','PAYS DE LA LOIRE','Pays de la Loire');
INSERT INTO "region"(code, "codecheflieu", "typenomclair", libelle, "libelleenrichi") VALUES ('53','35238','0','BRETAGNE','Bretagne');
INSERT INTO "region"(code, "codecheflieu", "typenomclair", libelle, "libelleenrichi") VALUES ('54','86194','2','POITOU-CHARENTES','Poitou-Charentes');
INSERT INTO "region"(code, "codecheflieu", "typenomclair", libelle, "libelleenrichi") VALUES ('72','33063','1','AQUITAINE','Aquitaine');
INSERT INTO "region"(code, "codecheflieu", "typenomclair", libelle, "libelleenrichi") VALUES ('73','31555','0','MIDI-PYRENEES','Midi-Pyrénées');
INSERT INTO "region"(code, "codecheflieu", "typenomclair", libelle, "libelleenrichi") VALUES ('74','87085','2','LIMOUSIN','Limousin');
INSERT INTO "region"(code, "codecheflieu", "typenomclair", libelle, "libelleenrichi") VALUES ('82','69123','2','RHONE-ALPES','Rhône-Alpes');
INSERT INTO "region"(code, "codecheflieu", "typenomclair", libelle, "libelleenrichi") VALUES ('83','63113','1','AUVERGNE','Auvergne');
INSERT INTO "region"(code, "codecheflieu", "typenomclair", libelle, "libelleenrichi") VALUES ('91','34172','2','LANGUEDOC-ROUSSILLON','Languedoc-Roussillon');
INSERT INTO "region"(code, "codecheflieu", "typenomclair", libelle, "libelleenrichi") VALUES ('93','13055','0','PROVENCE-ALPES-COTE D''AZUR','Provence-Alpes-Côte d''Azur');
INSERT INTO "region"(code, "codecheflieu", "typenomclair", libelle, "libelleenrichi") VALUES ('94','2A004','0','CORSE','Corse');
